### ISSUE TITLE
Error when a code that imports TPromise runs.

### ISSUE THREAD

**Issue by Judahh** [kshshe/ThreadPromises#6]
First of all I'm using Next.js. 
The following error occurs when a code that imports TPromise runs:
```
/Users/judah/auth/node_modules/thread-promises/index.js:1
import TPromise from "./src/TPromise";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:991:16)
    at Module._compile (internal/modules/cjs/loader.js:1039:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Object.require.extensions.<computed> [as .js] (/Users/judah/auth/node_modules/ts-node/src/index.ts:1045:43)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at eval (webpack-internal:///thread-promises:1:18)
    at Object.thread-promises (/Users/judah/auth/.next/server/pages/api/signUp.js:595:1)
    at __webpack_require__ (/Users/judah/auth/.next/server/pages/api/signUp.js:23:31)
    at eval (webpack-internal:///./src/routes/index.ts:21:74)
    at Module../src/routes/index.ts (/Users/judah/auth/.next/server/pages/api/signUp.js:342:1)
    at __webpack_require__ (/Users/judah/auth/.next/server/pages/api/signUp.js:23:31)
    at resolver (webpack-internal:///./src/pages/api/signUp/signUpHandler.ts:26:19)
    at apiResolver (/Users/judah/auth/node_modules/next/next-server/server/api-utils.ts:86:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at DevServer.handleApiRequest (/Users/judah/auth/node_modules/next/next-server/server/next-server.ts:1080:5)
    at Object.fn (/Users/judah/auth/node_modules/next/next-server/server/next-server.ts:954:27)
    at Router.execute (/Users/judah/auth/node_modules/next/next-server/server/router.ts:247:24)
    at DevServer.run (/Users/judah/auth/node_modules/next/next-server/server/next-server.ts:1179:23)
(node:22193) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by kshshe** [comment]
Hello!

I didn’t expect anyone to try TPromise so much that I just found out about the issue. Indeed, there was a problem with exports, now it should work.
